config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  resources :reclamacao

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reclamacao.rb
class Reclamacao < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reclamacao_controller.rb
class ReclamacaoController < ApplicationController

    def index
        @reclamacao = Reclamacao.all
    end
    
    def new
        @reclamacao = Reclamacao.new
    end

    def create
        @reclamacao = Reclamacao.new(reclamacao_params)
        @reclamacao.ip = get_ip

        responseIp = Faraday.get 'http://extreme-ip-lookup.com/json/' + @reclamacao.ip

        cep = get_cep_data(@reclamacao.cep)
        if cep.nil?
            flash[:mensagem] = "CEP invalido"
            redirect_to request.referrer
        else
            if cep["localidade"] == JSON.parse(responseIp.body)["city"]
                @reclamacao.suspeito = 'N'
            else
                @reclamacao.suspeito = 'S'
            end

            if @reclamacao.save
                flash[:mensagem] = "Reclamação realizada com sucesso. Ticket #" + @reclamacao.id.to_s
            else
                flash[:mensagem] = "Erro ao cadastrar a reclamação. Entre em contato com o suporte."
            end
            redirect_to :controller => 'reclamacao', action: 'index'
        end
    end
    
    def show
        begin  
            @reclamacao = Reclamacao.find(params[:id])
        rescue ActiveRecord::RecordNotFound  => e
            flash[:mensagem] = "Reclamação não encontrada"
            redirect_to :controller => 'reclamacao', action: 'index'
        end
    end

    private
        def reclamacao_params
            params.require(:reclamacao).permit(:nome, :cep, :email, :telefone, :cod_pedido, :titulo, :descricao, :suspeito)
        end

    private
        def get_cep_data(cep)            
            response = Faraday.get 'https://viacep.com.br/ws/'+cep.to_s+'/json/'
            if response.status == 200
                JSON.parse(response.body)
            else
                nil
            end
        end

    private
        def get_ip
            if request.local?
                '127.0.0.1'
            else
                request.remote_ip
            end
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navigation.html.erb
<%= link_to "Reclame Ai!", root_path, :class => 'navbar-brand' %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarResponsive">
<ul class="navbar-nav ml-auto">
    <li class="nav-item active">
        <%= link_to "Home", root_path, :class => 'nav-link' %>
    </li>
    <li class="nav-item">
        <%= link_to "Reclamar", new_reclamacao_path, :class => 'nav-link' %>
    </li>
    <li class="nav-item">
        <%= link_to "Visualizar", {controller: "reclamacao", action: "index"}, :class => 'nav-link' %>
    </li>          
</ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ReclameAi!" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    
    <header class="navbar navbar-fixed-top">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>

    <div id="main" role="main">
      <br /><br />
      <div class="container">
        <%= yield %>       
      </div> <!--! end of .container -->
      
      <br />
      <footer class="py-5 bg-dark">
        <div class="container">
          <p class="m-0 text-center text-white">Copyright &copy; brenovit 2019</p>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/reclamacao/index.html.erb
<% if flash[:mensagem] %>    
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <%= flash[:mensagem] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<% end %>

<div class="container">
    <% if @reclamacao.nil? || @reclamacao.empty? %>
        <div class="card text-white bg-secondary my-5 py-4 text-center">
            <div class="card-body">
                <p class="text-white m-0">Nenhuma reclamação registrada!</p>
            </div>
        </div>
    <% else %>
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Cliente</th>
                    <th scope="col">Titulo</th>
                    <th scope="col">CEP</th>
                    <th scope="col">IP</th>      
                    <th scope="col">Data Cadastro</th>       
                    <th scope="col">Rec. Suspeita</th>
                    <th scope="col">Ação</th>
                </tr>
            </thead>
            <tbody>
                <% @reclamacao.each do |rec| %>
                    <tr>
                        <th scope="row"><%=rec.id%></th>
                        <td><%= rec.nome %></td>
                        <td><%=rec.titulo%></td>
                        <td><%=rec.cep%></td>
                        <td><%=rec.ip%></td>
                        <td><%=rec.created_at.strftime("%d/%m/%Y")%>
                        </td><td><%=rec.suspeito == 'S' ? 'SIM' : 'NÃO' %></td>
                        <td><%= link_to "Visualizar", reclamacao_path(rec) %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    <% end %>
</div>

app/views/reclamacao/new.html.erb
<% if flash[:mensagem] %>    
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <%= flash[:mensagem] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<% end %>
<h3>Registrar Reclamação</h3>
<hr>
<%= form_with html:{class:"form", role:"form"}, scope: :reclamacao, url:reclamacao_index_path, local: true do |form| %>

    <div class="form-row">
        <div class="form-group col-md-6">
            <%= form.label :nome %>
            <%= form.text_field :nome, type:'text',
                class: 'form-control', placeholder:'Nome completo' %>
        </div>
        <div class="form-group col-md-2">
            <%= form.label :cep %>
            <%= form.text_field :cep,type:'text', 
                class: 'form-control', placeholder:'40000900'%>
        </div>
        <div class="form-group col-md-4">
            <%= form.label :email %>
            <%= form.text_field :email,type:'text',
                class: 'form-control', placeholder:'email@email.com' %>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-4">
            <%= form.label :telefone %>
            <%= form.text_field :telefone, 
                class: 'form-control', type:'text', placeholder:'DDD + Número', maxlength:'15' %>
        </div>

        <div class="form-group col-md-4">
            <%= form.label "Código Pedido" %>
            <%= form.text_field :cod_pedido, 
                class: 'form-control', type:'text', placeholder:'WXZ123456', maxlength:'40' %>
        </div>
    </div>

    <div class="form-group">
        <%= form.label :título %>
        <%= form.text_field :titulo,
            class: 'form-control', type:'text', placeholder:'Informe o título da reclamação', maxlength:'40' %>
    </div>

    <div class="form-group">
        <%= form.label :descrição %><br>
        <%= form.text_area :descricao,  class:'form-control' %>    
    </div>   

    <%= form.submit 'Salvar', class:'btn btn-primary' %>    
<% end %>

app/views/reclamacao/show.html.erb
<h3>Visualizar Reclamação</h3>
<hr>
<%= form_with html:{class:"form", role:"form"}, method:'get', scope: :reclamacao, url:reclamacao_index_path, local: true do |form| %>

    <div class="form-row">
        <div class="form-group col-md-6">
            <%= form.label :nome %>
            <%= form.text_field :nome, class: 'form-control', :readonly => true %>
        </div>
        <div class="form-group col-md-2">
            <%= form.label :cep %>
            <%= form.text_field :cep, class: 'form-control', :readonly => true %>
        </div>
        <div class="form-group col-md-4">
            <%= form.label :email %>
            <%= form.text_field :email, class: 'form-control', :readonly => true %>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-4">
            <%= form.label :telefone %>
            <%= form.text_field :telefone, class: 'form-control', :readonly => true %>
        </div>

        <div class="form-group col-md-4">
            <%= form.label "Código Pedido" %>
            <%= form.text_field :cod_pedido, class: 'form-control', :readonly => true %>
        </div>

        <div class="form-group col-md-4">
            <%= form.label :suspeito %>
            <%= form.text_field :suspeito, class: 'form-control', :readonly => true %>
        </div>
    </div>

    <div class="form-group">
        <%= form.label :título %>
        <%= form.text_field :titulo, class: 'form-control', :readonly => true %>
    </div>

    <div class="form-group">
        <%= form.label :reclamação %><br>
        <%= form.text_area :descricao,  class:'form-control', :readonly => true %>    
    </div>   

<% end %>

app/views/welcome/index.html.erb
<!-- Heading Row -->
<div class="row align-items-center my-5">
    <div class="col-lg-7">
    <img class="img-fluid rounded mb-4 mb-lg-0" width="80%" src="https://www.jota.info/wp-content/uploads/2018/04/feedback-3239758_1280-e1522959423977-1024x650.jpg" alt="">
    </div>
    <!-- /.col-lg-8 -->
    <div class="col-lg-4">
    <h1 class="font-weight-light">Bem vindo ao ReclameAi!</h1>
    <p>O melhor portal de comunicação pós venda do Brasil. Poste sua experiência com nossos produtos para entrarmos em contato com você e oferecer o melhor serviço.</p>        
    </div>
    <!-- /.col-md-4 -->
</div>
<!-- /.row -->
<!-- Content Row -->
<div class="row">
    <div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
        <h2 class="card-title">Cliente</h2>
        <p class="card-text">Queremos melhorar cada dia mais para oferecer um serviço de altissima qualidade. Nos informe sua situação para podemos te ajudar.</p>
        </div>
        <div class="card-footer">
            <%= link_to "Reclamar", new_reclamacao_path, :class => 'btn btn-primary btn-sm' %>
        </div>
    </div>
    </div>
    <!-- /.col-md-4 -->
    <div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
        <h2 class="card-title">Vendedor</h2>
        <p class="card-text">Acompanhe as reclamações feitas até o momento por cada usuario, oferecendo um melhor atendimento ao cliente.</p>
        </div>
        <div class="card-footer">
            <%= link_to "Acompanhar", {controller: "reclamacao", action: "index"}, :class => 'btn btn-primary btn-sm' %>
        </div>
    </div>
    </div>
    <!-- /.col-md-4 -->

</div>
<!-- /.row -->